apiVersion: apps/v1
kind: Deployment
metadata:
  name: blend-backend
  namespace: blend-backend
  labels:
    app: blend-backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blend-backend
  template:
    metadata:
      labels:
        app: blend-backend
        version: v1
    spec:
      containers:
      - name: blend-backend
        image: 287030536891.dkr.ecr.ap-south-1.amazonaws.com/blend/blend-services:latest
        ports:
        - containerPort: 5050
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: blend-backend-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: blend-backend-config
              key: PORT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: blend-backend-config
              key: LOG_LEVEL
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: blend-backend-config
              key: CORS_ORIGIN
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: blend-backend-config
              key: JWT_EXPIRES_IN
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: blend-backend-secrets
              key: MONGODB_URI
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5050
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
